# Generated by Django 5.2.11 on 2026-04-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_tool', '0008_alter_importtask_router_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtask',
            name='router_type',
            field=models.CharField(choices=[('cisco-ios', 'Cisco (IOS)'), ('cisco-xe', 'Cisco (IOS-XE)'), ('mikrotik', 'Mikrotik (RouterOS)'), ('mikrotik-branded', 'Mikrotik (Branded)'), ('openwrt', 'OpenWRT'), ('ubiquiti-airos', 'Ubiquiti airOS'), ('monitoring', 'Monitoring Only')], max_length=100),
        ),
    ]
