# Generated by Django 5.2.11 on 2026-04-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_tool', '0009_alter_importtask_router_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importtask',
            name='ssh_key_name',
        ),
    ]
