# Generated by Django 5.2.11 on 2026-04-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_commander', '0004_commandjob_aborted_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandvariant',
            name='router_type',
            field=models.CharField(choices=[('monitoring', 'Monitoring Only'), ('routeros', 'Mikrotik (RouterOS)'), ('routeros-branded', 'Mikrotik (Branded)'), ('cisco-ios', 'Cisco (IOS)'), ('cisco-xe', 'Cisco (IOS-XE)'), ('openwrt', 'OpenWRT'), ('ubiquiti-airos', 'Ubiquiti airOS')], max_length=100),
        ),
    ]
