# Generated by Django 5.2.11 on 2026-04-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0021_routerstatus_command_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='connection_protocol',
            field=models.CharField(choices=[('ssh', 'SSH'), ('telnet', 'Telnet')], default='ssh', max_length=10),
        ),
        migrations.AlterField(
            model_name='router',
            name='router_type',
            field=models.CharField(choices=[('monitoring', 'Monitoring Only'), ('routeros', 'Mikrotik (RouterOS)'), ('routeros-branded', 'Mikrotik (Branded)'), ('cisco-ios', 'Cisco (IOS)'), ('cisco-xe', 'Cisco (IOS-XE)'), ('openwrt', 'OpenWRT'), ('ubiquiti-airos', 'Ubiquiti airOS')], max_length=100),
        ),
    ]
