# Generated by Django 5.2.11 on 2026-04-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0023_alter_router_router_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='router',
            name='ssh_key',
        ),
    ]
