# Generated by Django 5.2.11 on 2026-04-28 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0024_remove_router_ssh_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SSHKey',
        ),
    ]
