# Generated by Django 5.2.11 on 2026-04-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0025_delete_sshkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupschedule',
            name='next_hourly_backup',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
