# Generated by Django 5.2.11 on 2026-04-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0026_backupschedule_next_hourly_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='ssh_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
