# Generated by Django 5.2.11 on 2026-04-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0027_router_ssh_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routergroup',
            options={'verbose_name': 'Nodo', 'verbose_name_plural': 'Nodos'},
        ),
    ]
