# Generated by Django 5.2.11 on 2026-05-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0028_alter_routergroup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='router',
            options={'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterField(
            model_name='router',
            name='address',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
