# Generated by Django 5.2.11 on 2026-05-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_alter_useracl_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useracl',
            name='user_level',
            field=models.PositiveIntegerField(choices=[(10, 'Visor'), (20, 'Operador de Respaldos'), (30, 'Gestor de Equipos'), (40, 'Gestor de Configuración'), (50, 'Administrador')], default=0),
        ),
    ]
