# Generated by Django 5.2.11 on 2026-05-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_center', '0007_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagechannel',
            name='channel_type',
            field=models.CharField(choices=[('callmebot', 'CallMeBot (WhatsApp)'), ('ntfy', 'ntfy.sh'), ('email', 'Email')], max_length=100),
        ),
    ]
