# Generated by Django 5.2.11 on 2026-04-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0009_backupprofile_parameter_sensitive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupprofile',
            name='hourly_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backupprofile',
            name='hourly_interval',
            field=models.IntegerField(choices=[(1, 'Every 1 hour'), (2, 'Every 2 hours'), (4, 'Every 4 hours'), (6, 'Every 6 hours'), (8, 'Every 8 hours'), (12, 'Every 12 hours')], default=6),
        ),
        migrations.AddField(
            model_name='backupprofile',
            name='hourly_retention',
            field=models.IntegerField(default=3),
        ),
    ]
