# Generated by Django 5.2.11 on 2026-05-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0010_backupprofile_hourly_backup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupprofile',
            name='backup_interval',
            field=models.IntegerField(choices=[(0, 'Sin intervalo'), (5, '5 segundos'), (60, '1 minuto')], default=0),
        ),
        migrations.AlterField(
            model_name='backupprofile',
            name='hourly_interval',
            field=models.IntegerField(choices=[(1, 'Cada 1 hora'), (2, 'Cada 2 horas'), (4, 'Cada 4 horas'), (6, 'Cada 6 horas'), (8, 'Cada 8 horas'), (12, 'Cada 12 horas')], default=6),
        ),
        migrations.AlterField(
            model_name='backupprofile',
            name='monthly_day',
            field=models.IntegerField(choices=[(1, '1º'), (7, '7º'), (14, '14º'), (21, '21º'), (28, '28º')], default=1),
        ),
        migrations.AlterField(
            model_name='backupprofile',
            name='retrieve_interval',
            field=models.IntegerField(choices=[(15, '15 Segundos'), (30, '30 Segundos'), (60, '1 Minuto'), (900, '15 Minutos'), (1800, '30 Minutos'), (3600, '1 Hora')], default=60),
        ),
        migrations.AlterField(
            model_name='backupprofile',
            name='retry_interval',
            field=models.IntegerField(choices=[(1, '1 Minuto'), (15, '15 Minutos'), (30, '30 Minutos'), (60, '1 Hora')], default=30),
        ),
        migrations.AlterField(
            model_name='backupprofile',
            name='weekly_day',
            field=models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], default='sunday', max_length=10),
        ),
    ]
