# Generated by Django 5.2.11 on 2026-04-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_data', '0011_routerbackup_task_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerbackup',
            name='identical_to_previous',
            field=models.BooleanField(default=False),
        ),
    ]
